---
title: "Exploratory Data Analysis"
author: "Michael Wu"
date: "2023-11-30"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
      toc_selector: "#toc"
      width: 300px
      align: left
    css: styles.css
---

<style>
body {
  font-size: 16px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r}
# load library
library(tidyverse)
library(DataExplorer)
source(here::here("R/functions.R"))

# manually change this to the box path on your computer if using Windows
box_path <- "~/Library/CloudStorage/Box-Box/Dads Matter Project"

# load data
dat_f <- read_csv(file.path(box_path, "Data analysis/data/dads_matter_fa_comp.csv"))

dat_f_1 <- dat_f |> select(ends_with("_1") & !starts_with("cts_"))
dat_f_2 <- dat_f |> select(ends_with("_2") & !starts_with("cts_"))

```

```{r}
dat_f_1 |>
    create_report(
        output_dir = "analysis",
        output_file = "EDA_report_T1.html",
        report_title = "EDA Report T1",
        config = configure_report(add_plot_str = F,
                                  add_plot_qq = F,
                                  add_plot_bar = F,
                                  add_plot_prcomp = F,
                                  plot_histogram_args = list(nrow = 6,
                                                             ncol = 7,
                                                             binary_as_factor = F)
                                  )
    )

dat_f_2 |>
    create_report(
        output_dir = "analysis",
        output_file = "EDA_report_T2.html",
        report_title = "EDA Report T2",
        config = configure_report(add_plot_str = F,
                                  add_plot_qq = F,
                                  add_plot_bar = F,
                                  add_plot_prcomp = F,
                                  plot_histogram_args = list(nrow = 6,
                                                             ncol = 7,
                                                             binary_as_factor = F)
                                  )
    )

```

```{r}
cor_1 <- corstarsl(dat_f_1) |> as.data.frame()

write.csv(cor_1, file.path(box_path, "Data analysis/data/cor_mat_1.csv"))

cor_2 <- corstarsl(dat_f_2) |> as.data.frame()

write.csv(cor_2, file.path(box_path, "Data analysis/data/cor_mat_2.csv"))

```

```{r}
library(naniar)
vis_miss(dat_f_1) + theme(axis.text.x = element_text(angle=80))
vis_miss(dat_f_2) + theme(axis.text.x = element_text(angle=80))

gg_miss_upset(dat_f_1, nsets = 10)
gg_miss_upset(dat_f_2, nsets = 10)

gg_miss_upset(dat_f |> select(c_overall_z_1:pers_overall_z_1))
gg_miss_upset(dat_f |> select(mfi_fs_m_1:cts_sex_abuse_partner_f_1), nsets = 10)

gg_miss_upset(dat_f |> select(c_overall_z_2:pers_overall_z_2))
gg_miss_upset(dat_f |> select(mfi_fs_m_2:cts_sex_abuse_partner_f_2), nsets = 10)

```

